#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")"
REPO_FOLDER="$(dirname "$SCRIPT_PATH")"
PREV_CWD=$(pwd)

pytest "$REPO_FOLDER"
RES_PYTEST=$?

cd "$REPO_FOLDER/example_projects"
./run_all_examples.sh
RES_EXAMPLES=$?

cd "$PREV_CWD"

echo -e "\n\n"

echo "pytest:           $([[ $RES_PYTEST   == 0 ]] && echo Passed || echo Failed)"
echo "example_projects: $([[ $RES_EXAMPLES == 0 ]] && echo Passed || echo Failed)"

# Exit with failure if either failed
[[ $RES_PYTEST == 0 && $RES_EXAMPLES == 0 ]]