# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_export_as_func.ipynb

# %% nbs/03_export_as_func.ipynb 8
# Validate input
if not isinstance(input_list, list):
    raise TypeError("input_list must be a list")

# %% nbs/03_export_as_func.ipynb 9
# Process the data
result = [x * multiplier for x in input_list]

# %% nbs/03_export_as_func.ipynb 11
result
