# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_export_to.ipynb

__all__ = ['explicit_module', 'regular_export', 'with_order']

# %% nbs/02_export_to.ipynb 3
def regular_export():
    """Exported with standard #|export directive."""
    return "regular"

# %% nbs/02_export_to.ipynb 5
def explicit_module():
    """Explicitly specifies the target module."""
    return "explicit"

# %% nbs/02_export_to.ipynb 6
def with_order():
    """Specifies module and order (lower = earlier in file)."""
    return "ordered"
